### ISSUE TITLE
Stage: Deploy Improvements

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous#43]
The deploy stage is a good start but there are some improvements needed to be useful for real deployments.
- [x] Variable support for updating a manifest before deployment (perhaps adding gotmpl support and/or a regex)
- [ ] Deploy to different namespace (eg. `<basenamespace>-staging` or `<basenamespace>-<commitid>`). Regex/Variable support useful here too?
- [ ] Image Tag handling - deploying the image built in an earlier stage. Another variable to be used in a template?
- [x] `kubectl apply` support - updating existing resources in place

Perhaps it is easier to use `kubectl` directly for the stage instead of the API

A few of these ideas are coming from the GCE CD Jenkins example (https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/sample-app/Jenkinsfile#L39-L48)

**Comment by hunter** [comment]
Helm uses a similar approach for their values/templates - https://github.com/kubernetes/helm/blob/master/docs/charts.md#templates-and-values

**Comment by madziefe** [comment]
For variables we can use gotemplate and toml to provide the values. 
we can add `value_file` or any better name for that? as param in deploy 

``` yaml
      - name: Deploy App
        type: deploy
        params:
          deploy_file: manifest.yml
          value_file: manifest.toml
```

If value_file is left empty, then will run/apply manifest.yml as is.

**Comment by hunter** [comment]
A few alternatives to consider too...

KVs in the yaml:

``` yaml
      - name: Deploy App
        type: deploy
        params:
          deploy_file: manifest.yml
        vars:
          value1: something
          value2: somethingelse
```

or otherwise ConfigMaps

One consideration with any of these options is how do we handle/specify global variables (commit id, tags, etc) or pass vars them between stages

**Comment by madziefe** [comment]
for approach 1 these are the sample files:

manifest.yml

```
---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: {{default "kontinuous" .namespace}}

spec:
  selector:
    app: {{.name}}
    type: ci-cd
  ports:
    - name: api
      port: 8080
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: {{default "kontinuous" .namespace}}
  labels:
    app: {{.name}}
    type: ci-cd    
spec:
  containers:
    - name: {{.name}}
      image: {{.imageRegistry}}/{{.imageName}}:{{.dockerTag}}
      imagePullPolicy: {{.pullPolicy}}
      ports:
        - name: api
          containerPort: 8080
          protocol: TCP
```

manifest.toml

```
dockerTag = "latest"
pullPolicy = "Always"
name = "myproj"
namespace = "mayspace"
imageRegistry = "quay.io/myrepo"
imageName = "myprojimage"
```
