### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by darkcrux** [AcalephStorage/kontinuous#67]
Following the jenkinsfile example, we need to define a way to handle branches, after a long discussion/argument over the same solution, @madziefe and I came up with something like this:

```
...
stages:
  - name: Build Image
    type: docker_build
  - name: Run Tests
    type: command
    params:
      ...
  - name: Publish image
    type: docker_publish
  - name: handle branches
    type: multi_branch
    params:
      branches:
        staging:
          - type: command
            params: ...
          - type: command
            params: ...
        master:
           ...
        default**:
           ... 
```

So far, we think this is a flexible way of handling branches. basically when a build is created, the multi-branch part will get parsed and the actual list of stages will be added to pipeline. the `default**` means it's the behaviour if no branch is matched.
